name: SkyBlock
description: A powerful core for SkyBlock servers
author: room17
website: twitter.com/room17
main: room17\SkyBlock\SkyBlock
version: 3.0.0
api: 3.0.0

permissions:
  skyblock.interaction:
    description: Allows players to interact with an island regardless of whether they belong to it
    default: op